import type { Q } from "./Q";

export const data: Q[] = [
    { en: "come", de: "Kommen Sie", category: "Operations" },
    { en: "get", de: "erhalten", category: "Operations" },
    { en: "give", de: "geben", category: "Operations" },
    { en: "go", de: "gehen", category: "Operations" },
    { en: "keep", de: "behalten", category: "Operations" },
    { en: "let", de: "Lassen", category: "Operations" },
    { en: "make", de: "machen", category: "Operations" },
    { en: "put", de: "stellen", category: "Operations" },
    { en: "seem", de: "scheinen", category: "Operations" },
    { en: "take", de: "nehmen", category: "Operations" },
    { en: "be", de: "Sein", category: "Operations" },
    { en: "do", de: "machen", category: "Operations" },
    { en: "have", de: "haben", category: "Operations" },
    { en: "say", de: "sagen", category: "Operations" },
    { en: "see", de: "sehen", category: "Operations" },
    { en: "send", de: "senden", category: "Operations" },
    { en: "may", de: "kann", category: "Operations" },
    { en: "will", de: "werden", category: "Operations" },
    { en: "about", de: "Über", category: "Operations" },
    { en: "across", de: "über", category: "Operations" },
    { en: "after", de: "nach dem", category: "Operations" },
    { en: "against", de: "gegen", category: "Operations" },
    { en: "among", de: "unter", category: "Operations" },
    { en: "at", de: "beim", category: "Operations" },
    { en: "before", de: "Vor", category: "Operations" },
    { en: "between", de: "zwischen", category: "Operations" },
    { en: "by", de: "durch", category: "Operations" },
    { en: "down", de: "Nieder", category: "Operations" },
    { en: "from", de: "von", category: "Operations" },
    { en: "in", de: "im", category: "Operations" },
    { en: "off", de: "aus", category: "Operations" },
    { en: "on", de: "auf", category: "Operations" },
    { en: "over", de: "Über", category: "Operations" },
    { en: "through", de: "durch", category: "Operations" },
    { en: "to", de: "zu", category: "Operations" },
    { en: "under", de: "unter", category: "Operations" },
    { en: "up", de: "oben", category: "Operations" },
    { en: "with", de: "mit", category: "Operations" },
    { en: "as", de: "wie", category: "Operations" },
    { en: "for", de: "zum", category: "Operations" },
    { en: "of", de: "von", category: "Operations" },
    { en: "till", de: "bis", category: "Operations" },
    { en: "than", de: "als", category: "Operations" },
    { en: "a", de: "ein", category: "Operations" },
    { en: "the", de: "das", category: "Operations" },
    { en: "all", de: "alles", category: "Operations" },
    { en: "any", de: "irgendein", category: "Operations" },
    { en: "every", de: "jeder", category: "Operations" },
    { en: "little", de: "wenig", category: "Operations" },
    { en: "much", de: "viel", category: "Operations" },
    { en: "no", de: "Nein", category: "Operations" },
    { en: "other", de: "andere", category: "Operations" },
    { en: "some", de: "etwas", category: "Operations" },
    { en: "such", de: "eine solche", category: "Operations" },
    { en: "that", de: "Das", category: "Operations" },
    { en: "this", de: "diese", category: "Operations" },
    { en: "I", de: "ich", category: "Operations" },
    { en: "he", de: "er", category: "Operations" },
    { en: "you", de: "Sie", category: "Operations" },
    { en: "who", de: "die", category: "Operations" },
    { en: "and", de: "und", category: "Operations" },
    { en: "because", de: "weil", category: "Operations" },
    { en: "but", de: "aber", category: "Operations" },
    { en: "or", de: "oder", category: "Operations" },
    { en: "if", de: "wenn", category: "Operations" },
    { en: "though", de: "obwohl", category: "Operations" },
    { en: "while", de: "während", category: "Operations" },
    { en: "how", de: "Wie", category: "Operations" },
    { en: "when", de: "wann", category: "Operations" },
    { en: "where", de: "wo", category: "Operations" },
    { en: "why", de: "Warum", category: "Operations" },
    { en: "again", de: "nochmal", category: "Operations" },
    { en: "ever", de: "je", category: "Operations" },
    { en: "far", de: "weit", category: "Operations" },
    { en: "forward", de: "nach vorne", category: "Operations" },
    { en: "here", de: "Hier", category: "Operations" },
    { en: "near", de: "in der Nähe von", category: "Operations" },
    { en: "now", de: "jetzt", category: "Operations" },
    { en: "out", de: "aus", category: "Operations" },
    { en: "still", de: "immer noch", category: "Operations" },
    { en: "then", de: "dann", category: "Operations" },
    { en: "there", de: "Dort", category: "Operations" },
    { en: "together", de: "zusammen", category: "Operations" },
    { en: "well", de: "Gut", category: "Operations" },
    { en: "almost", de: "fast", category: "Operations" },
    { en: "enough", de: "genug", category: "Operations" },
    { en: "even", de: "sogar", category: "Operations" },
    { en: "not", de: "nicht", category: "Operations" },
    { en: "only", de: "nur", category: "Operations" },
    { en: "quite", de: "ganz", category: "Operations" },
    { en: "so", de: "damit", category: "Operations" },
    { en: "very", de: "sehr", category: "Operations" },
    { en: "tomorrow", de: "Morgen", category: "Operations" },
    { en: "yesterday", de: "gestern", category: "Operations" },
    { en: "north", de: "Norden", category: "Operations" },
    { en: "south", de: "Süd", category: "Operations" },
    { en: "east", de: "Osten", category: "Operations" },
    { en: "west", de: "Westen", category: "Operations" },
    { en: "please", de: "Bitte", category: "Operations" },
    { en: "yes", de: "Ja", category: "Operations" },

    { en: "account", de: "Konto", category: "Things - General" },
    { en: "act", de: "Handlung", category: "Things - General" },
    { en: "addition", de: "Zusatz", category: "Things - General" },
    { en: "adjustment", de: "Einstellung", category: "Things - General" },
    { en: "advertisement", de: "Werbung", category: "Things - General" },
    { en: "agreement", de: "Zustimmung", category: "Things - General" },
    { en: "air", de: "Luft", category: "Things - General" },
    { en: "amount", de: "Menge", category: "Things - General" },
    { en: "amusement", de: "Amüsement", category: "Things - General" },
    { en: "animal", de: "Tier", category: "Things - General" },
    { en: "answer", de: "Antworten", category: "Things - General" },
    { en: "apparatus", de: "Gerät", category: "Things - General" },
    { en: "approval", de: "die Genehmigung", category: "Things - General" },
    { en: "argument", de: "Streit", category: "Things - General" },
    { en: "art", de: "Kunst", category: "Things - General" },
    { en: "attack", de: "Attacke", category: "Things - General" },
    { en: "attempt", de: "Versuch", category: "Things - General" },
    { en: "attention", de: "Beachtung", category: "Things - General" },
    { en: "attraction", de: "Attraktion", category: "Things - General" },
    { en: "authority", de: "Behörde", category: "Things - General" },
    { en: "back", de: "zurück", category: "Things - General" },
    { en: "balance", de: "Balance", category: "Things - General" },
    { en: "base", de: "Base", category: "Things - General" },
    { en: "behavior", de: "Verhalten", category: "Things - General" },
    { en: "belief", de: "Glauben", category: "Things - General" },
    { en: "birth", de: "Geburt", category: "Things - General" },
    { en: "bit", de: "bisschen", category: "Things - General" },
    { en: "bite", de: "beißen", category: "Things - General" },
    { en: "blood", de: "Blut", category: "Things - General" },
    { en: "blow", de: "Schlag", category: "Things - General" },
    { en: "body", de: "Körper", category: "Things - General" },
    { en: "brass", de: "Messing-", category: "Things - General" },
    { en: "bread", de: "Brot", category: "Things - General" },
    { en: "breath", de: "Atem", category: "Things - General" },
    { en: "brother", de: "Bruder", category: "Things - General" },
    { en: "building", de: "Gebäude", category: "Things - General" },
    { en: "burn", de: "brennen", category: "Things - General" },
    { en: "burst", de: "platzen", category: "Things - General" },
    { en: "business", de: "Geschäft", category: "Things - General" },
    { en: "butter", de: "Butter", category: "Things - General" },
    { en: "canvas", de: "Segeltuch", category: "Things - General" },
    { en: "care", de: "Pflege", category: "Things - General" },
    { en: "cause", de: "Ursache", category: "Things - General" },
    { en: "chalk", de: "Kreide", category: "Things - General" },
    { en: "chance", de: "Chance", category: "Things - General" },
    { en: "change", de: "Veränderung", category: "Things - General" },
    { en: "cloth", de: "Stoff", category: "Things - General" },
    { en: "coal", de: "Kohle", category: "Things - General" },
    { en: "color", de: "Farbe", category: "Things - General" },
    { en: "comfort", de: "Komfort", category: "Things - General" },
    { en: "committee", de: "Komitee", category: "Things - General" },
    { en: "company", de: "Unternehmen", category: "Things - General" },
    { en: "comparison", de: "Vergleich", category: "Things - General" },
    { en: "competition", de: "Wettbewerb", category: "Things - General" },
    { en: "condition", de: "Bedingung", category: "Things - General" },
    { en: "connection", de: "Verbindung", category: "Things - General" },
    { en: "control", de: "Steuerung", category: "Things - General" },
    { en: "cook", de: "Koch", category: "Things - General" },
    { en: "copper", de: "Kupfer", category: "Things - General" },
    { en: "copy", de: "Kopieren", category: "Things - General" },
    { en: "cork", de: "Kork", category: "Things - General" },
    { en: "cotton", de: "Baumwolle", category: "Things - General" },
    { en: "cough", de: "Husten", category: "Things - General" },
    { en: "country", de: "Land", category: "Things - General" },
    { en: "cover", de: "Startseite", category: "Things - General" },
    { en: "crack", de: "Riss", category: "Things - General" },
    { en: "credit", de: "Anerkennung", category: "Things - General" },
    { en: "crime", de: "Kriminalität", category: "Things - General" },
    { en: "crush", de: "zerquetschen", category: "Things - General" },
    { en: "cry", de: "Weinen", category: "Things - General" },
    { en: "current", de: "Strom", category: "Things - General" },
    { en: "curve", de: "Kurve", category: "Things - General" },
    { en: "damage", de: "Beschädigung", category: "Things - General" },
    { en: "danger", de: "Achtung", category: "Things - General" },
    { en: "daughter", de: "Tochter", category: "Things - General" },
    { en: "day", de: "Tag", category: "Things - General" },
    { en: "death", de: "Tod", category: "Things - General" },
    { en: "debt", de: "Schuld", category: "Things - General" },
    { en: "decision", de: "Entscheidung", category: "Things - General" },
    { en: "degree", de: "Grad", category: "Things - General" },
    { en: "design", de: "Design", category: "Things - General" },
    { en: "desire", de: "Verlangen", category: "Things - General" },
    { en: "destruction", de: "Zerstörung", category: "Things - General" },
    { en: "detail", de: "Detail", category: "Things - General" },
    { en: "development", de: "Entwicklung", category: "Things - General" },
    { en: "digestion", de: "Verdauung", category: "Things - General" },
    { en: "direction", de: "Richtung", category: "Things - General" },
    { en: "discovery", de: "Entdeckung", category: "Things - General" },
    { en: "discussion", de: "Diskussion", category: "Things - General" },
    { en: "disease", de: "Krankheit", category: "Things - General" },
    { en: "disgust", de: "der Ekel", category: "Things - General" },
    { en: "distance", de: "Entfernung", category: "Things - General" },
    { en: "distribution", de: "Verteilung", category: "Things - General" },
    { en: "division", de: "Teilung", category: "Things - General" },
    { en: "doubt", de: "Zweifel", category: "Things - General" },
    { en: "drink", de: "Getränk", category: "Things - General" },
    { en: "driving", de: "Fahren", category: "Things - General" },
    { en: "dust", de: "Staub", category: "Things - General" },
    { en: "earth", de: "Erde", category: "Things - General" },
    { en: "edge", de: "Kante", category: "Things - General" },
    { en: "education", de: "Bildung", category: "Things - General" },
    { en: "effect", de: "bewirken", category: "Things - General" },
    { en: "end", de: "Ende", category: "Things - General" },
    { en: "error", de: "Error", category: "Things - General" },
    { en: "event", de: "Veranstaltung", category: "Things - General" },
    { en: "example", de: "Beispiel", category: "Things - General" },
    { en: "exchange", de: "Austausch-", category: "Things - General" },
    { en: "existence", de: "Existenz", category: "Things - General" },
    { en: "expansion", de: "Erweiterung", category: "Things - General" },
    { en: "experience", de: "Erfahrung", category: "Things - General" },
    { en: "expert", de: "Experte", category: "Things - General" },
    { en: "fact", de: "Tatsache", category: "Things - General" },
    { en: "fall", de: "fallen", category: "Things - General" },
    { en: "family", de: "Familie", category: "Things - General" },
    { en: "father", de: "Vater", category: "Things - General" },
    { en: "fear", de: "Angst", category: "Things - General" },
    { en: "feeling", de: "Gefühl", category: "Things - General" },
    { en: "fiction", de: "Fiktion", category: "Things - General" },
    { en: "field", de: "Feld", category: "Things - General" },
    { en: "fight", de: "Kampf", category: "Things - General" },
    { en: "fire", de: "Feuer", category: "Things - General" },
    { en: "flame", de: "Flamme", category: "Things - General" },
    { en: "flight", de: "Flug", category: "Things - General" },
    { en: "flower", de: "Blume", category: "Things - General" },
    { en: "fold", de: "falten", category: "Things - General" },
    { en: "food", de: "Lebensmittel", category: "Things - General" },
    { en: "force", de: "Macht", category: "Things - General" },
    { en: "form", de: "bilden", category: "Things - General" },
    { en: "friend", de: "Freund", category: "Things - General" },
    { en: "front", de: "Vorderseite", category: "Things - General" },
    { en: "fruit", de: "Obst", category: "Things - General" },
    { en: "glass", de: "Glas", category: "Things - General" },
    { en: "gold", de: "Gold", category: "Things - General" },
    { en: "government", de: "Regierung", category: "Things - General" },
    { en: "grain", de: "Korn", category: "Things - General" },
    { en: "grass", de: "Gras", category: "Things - General" },
    { en: "grip", de: "Griff", category: "Things - General" },
    { en: "group", de: "Gruppe", category: "Things - General" },
    { en: "growth", de: "Wachstum", category: "Things - General" },
    { en: "guide", de: "leiten", category: "Things - General" },
    { en: "harbor", de: "Hafen", category: "Things - General" },
    { en: "harmony", de: "Harmonie", category: "Things - General" },
    { en: "hate", de: "Hass", category: "Things - General" },
    { en: "hearing", de: "Hören", category: "Things - General" },
    { en: "heat", de: "Hitze", category: "Things - General" },
    { en: "help", de: "Hilfe", category: "Things - General" },
    { en: "history", de: "Geschichte", category: "Things - General" },
    { en: "hole", de: "Loch", category: "Things - General" },
    { en: "hope", de: "Hoffnung", category: "Things - General" },
    { en: "hour", de: "Stunde", category: "Things - General" },
    { en: "humor", de: "Humor", category: "Things - General" },
    { en: "ice", de: "Eis", category: "Things - General" },
    { en: "idea", de: "Idee", category: "Things - General" },
    { en: "impulse", de: "Impuls", category: "Things - General" },
    { en: "increase", de: "erhöhen, ansteigen", category: "Things - General" },
    { en: "industry", de: "Industrie", category: "Things - General" },
    { en: "ink", de: "Tinte", category: "Things - General" },
    { en: "insect", de: "Insekt", category: "Things - General" },
    { en: "instrument", de: "Instrument", category: "Things - General" },
    { en: "insurance", de: "Versicherung", category: "Things - General" },
    { en: "interest", de: "Interesse", category: "Things - General" },
    { en: "invention", de: "Erfindung", category: "Things - General" },
    { en: "iron", de: "Eisen", category: "Things - General" },
    { en: "jelly", de: "Gelee", category: "Things - General" },
    { en: "join", de: "beitreten", category: "Things - General" },
    { en: "journey", de: "Reise", category: "Things - General" },
    { en: "judge", de: "Richter", category: "Things - General" },
    { en: "jump", de: "springen", category: "Things - General" },
    { en: "kick", de: "trete", category: "Things - General" },
    { en: "kiss", de: "Kuss", category: "Things - General" },
    { en: "knowledge", de: "Wissen", category: "Things - General" },
    { en: "land", de: "Land", category: "Things - General" },
    { en: "language", de: "Sprache", category: "Things - General" },
    { en: "laugh", de: "Lachen", category: "Things - General" },
    { en: "law", de: "Recht", category: "Things - General" },
    { en: "lead", de: "führen", category: "Things - General" },
    { en: "learning", de: "Lernen", category: "Things - General" },
    { en: "leather", de: "Leder", category: "Things - General" },
    { en: "letter", de: "Brief", category: "Things - General" },
    { en: "level", de: "Niveau", category: "Things - General" },
    { en: "lift", de: "Aufzug", category: "Things - General" },
    { en: "light", de: "Licht", category: "Things - General" },
    { en: "limit", de: "Grenze", category: "Things - General" },
    { en: "linen", de: "Leinen-", category: "Things - General" },
    { en: "liquid", de: "Flüssigkeit", category: "Things - General" },
    { en: "list", de: "Liste", category: "Things - General" },
    { en: "look", de: "aussehen", category: "Things - General" },
    { en: "loss", de: "Verlust", category: "Things - General" },
    { en: "love", de: "Liebe", category: "Things - General" },
    { en: "machine", de: "Maschine", category: "Things - General" },
    { en: "man", de: "Mann", category: "Things - General" },
    { en: "manager", de: "Manager", category: "Things - General" },
    { en: "mark", de: "Kennzeichen", category: "Things - General" },
    { en: "market", de: "Markt", category: "Things - General" },
    { en: "mass", de: "Masse", category: "Things - General" },
    { en: "meal", de: "Mahlzeit", category: "Things - General" },
    { en: "measure", de: "messen", category: "Things - General" },
    { en: "meat", de: "Fleisch", category: "Things - General" },
    { en: "meeting", de: "Treffen", category: "Things - General" },
    { en: "memory", de: "Erinnerung", category: "Things - General" },
    { en: "metal", de: "Metall", category: "Things - General" },
    { en: "middle", de: "Mitte", category: "Things - General" },
    { en: "milk", de: "Milch", category: "Things - General" },
    { en: "mind", de: "Verstand", category: "Things - General" },
    { en: "mine", de: "Bergwerk", category: "Things - General" },
    { en: "minute", de: "Minute", category: "Things - General" },
    { en: "mist", de: "Nebel", category: "Things - General" },
    { en: "money", de: "Geld", category: "Things - General" },
    { en: "month", de: "Monat", category: "Things - General" },
    { en: "morning", de: "Morgen", category: "Things - General" },
    { en: "mother", de: "Mutter", category: "Things - General" },
    { en: "motion", de: "Bewegung", category: "Things - General" },
    { en: "mountain", de: "Berg", category: "Things - General" },
    { en: "move", de: "Bewegung", category: "Things - General" },
    { en: "music", de: "Musik-", category: "Things - General" },
    { en: "name", de: "Name", category: "Things - General" },
    { en: "nation", de: "Nation", category: "Things - General" },
    { en: "need", de: "brauchen", category: "Things - General" },
    { en: "news", de: "Nachrichten", category: "Things - General" },
    { en: "night", de: "Nacht-", category: "Things - General" },
    { en: "noise", de: "Lärm", category: "Things - General" },
    { en: "note", de: "Hinweis", category: "Things - General" },
    { en: "number", de: "Nummer", category: "Things - General" },
    { en: "observation", de: "Überwachung", category: "Things - General" },
    { en: "offer", de: "Angebot", category: "Things - General" },
    { en: "oil", de: "Öl", category: "Things - General" },
    { en: "operation", de: "Betrieb", category: "Things - General" },
    { en: "opinion", de: "Meinung", category: "Things - General" },
    { en: "order", de: "Auftrag", category: "Things - General" },
    { en: "organization", de: "Organisation", category: "Things - General" },
    { en: "ornament", de: "Ornament", category: "Things - General" },
    { en: "owner", de: "Inhaber", category: "Things - General" },
    { en: "page", de: "Seite", category: "Things - General" },
    { en: "pain", de: "Schmerzen", category: "Things - General" },
    { en: "paint", de: "Farbe", category: "Things - General" },
    { en: "paper", de: "Papier-", category: "Things - General" },
    { en: "part", de: "Teil", category: "Things - General" },
    { en: "paste", de: "Einfügen", category: "Things - General" },
    { en: "payment", de: "Zahlung", category: "Things - General" },
    { en: "peace", de: "Frieden", category: "Things - General" },
    { en: "person", de: "Person", category: "Things - General" },
    { en: "place", de: "Ort", category: "Things - General" },
    { en: "plant", de: "Pflanze", category: "Things - General" },
    { en: "play", de: "abspielen", category: "Things - General" },
    { en: "pleasure", de: "Vergnügen", category: "Things - General" },
    { en: "point", de: "Punkt", category: "Things - General" },
    { en: "poison", de: "Gift", category: "Things - General" },
    { en: "polish", de: "Polieren", category: "Things - General" },
    { en: "porter", de: "Porter", category: "Things - General" },
    { en: "position", de: "Position", category: "Things - General" },
    { en: "powder", de: "Pulver", category: "Things - General" },
    { en: "power", de: "Leistung", category: "Things - General" },
    { en: "price", de: "Preis", category: "Things - General" },
    { en: "print", de: "drucken", category: "Things - General" },
    { en: "process", de: "Prozess", category: "Things - General" },
    { en: "produce", de: "produzieren", category: "Things - General" },
    { en: "profit", de: "profitieren", category: "Things - General" },
    { en: "property", de: "Eigentum", category: "Things - General" },
    { en: "prose", de: "Prosa", category: "Things - General" },
    { en: "protest", de: "Protest", category: "Things - General" },
    { en: "pull", de: "ziehen", category: "Things - General" },
    { en: "punishment", de: "Bestrafung", category: "Things - General" },
    { en: "purpose", de: "Zweck", category: "Things - General" },
    { en: "push", de: "drücken", category: "Things - General" },
    { en: "quality", de: "Qualität", category: "Things - General" },
    { en: "question", de: "Frage", category: "Things - General" },
    { en: "rain", de: "Regen", category: "Things - General" },
    { en: "range", de: "Reichweite", category: "Things - General" },
    { en: "rate", de: "Bewertung", category: "Things - General" },
    { en: "ray", de: "Strahl", category: "Things - General" },
    { en: "reaction", de: "Reaktion", category: "Things - General" },
    { en: "reading", de: "lesen", category: "Things - General" },
    { en: "reason", de: "Grund", category: "Things - General" },
    { en: "record", de: "Aufzeichnung", category: "Things - General" },
    { en: "regret", de: "Bedauern", category: "Things - General" },
    { en: "relation", de: "Beziehung", category: "Things - General" },
    { en: "religion", de: "Religion", category: "Things - General" },
    { en: "representative", de: "Vertreter", category: "Things - General" },
    { en: "request", de: "Anfrage", category: "Things - General" },
    { en: "respect", de: "Respekt", category: "Things - General" },
    { en: "rest", de: "sich ausruhen", category: "Things - General" },
    { en: "reward", de: "Belohnung", category: "Things - General" },
    { en: "rhythm", de: "Rhythmus", category: "Things - General" },
    { en: "rice", de: "Reis", category: "Things - General" },
    { en: "river", de: "Fluss", category: "Things - General" },
    { en: "road", de: "Straße", category: "Things - General" },
    { en: "roll", de: "rollen", category: "Things - General" },
    { en: "room", de: "Zimmer", category: "Things - General" },
    { en: "rub", de: "reiben", category: "Things - General" },
    { en: "rule", de: "Regel", category: "Things - General" },
    { en: "run", de: "Lauf", category: "Things - General" },
    { en: "salt", de: "Salz-", category: "Things - General" },
    { en: "sand", de: "Sand", category: "Things - General" },
    { en: "scale", de: "Rahmen", category: "Things - General" },
    { en: "science", de: "Wissenschaft", category: "Things - General" },
    { en: "sea", de: "Meer", category: "Things - General" },
    { en: "seat", de: "Sitz", category: "Things - General" },
    { en: "secretary", de: "Sekretär", category: "Things - General" },
    { en: "selection", de: "Auswahl", category: "Things - General" },
    { en: "self", de: "selbst", category: "Things - General" },
    { en: "sense", de: "Sinn", category: "Things - General" },
    { en: "servant", de: "Diener", category: "Things - General" },
    { en: "sex", de: "Sex", category: "Things - General" },
    { en: "shade", de: "Schatten", category: "Things - General" },
    { en: "shake", de: "Shake", category: "Things - General" },
    { en: "shame", de: "Schande", category: "Things - General" },
    { en: "shock", de: "Schock", category: "Things - General" },
    { en: "side", de: "Seite", category: "Things - General" },
    { en: "sign", de: "Schild", category: "Things - General" },
    { en: "silk", de: "Seide", category: "Things - General" },
    { en: "silver", de: "Silber-", category: "Things - General" },
    { en: "sister", de: "Schwester", category: "Things - General" },
    { en: "size", de: "Größe", category: "Things - General" },
    { en: "sky", de: "Himmel", category: "Things - General" },
    { en: "sleep", de: "schlafen", category: "Things - General" },
    { en: "slip", de: "Unterhose", category: "Things - General" },
    { en: "slope", de: "Steigung", category: "Things - General" },
    { en: "smash", de: "Smash", category: "Things - General" },
    { en: "smell", de: "Geruch", category: "Things - General" },
    { en: "smile", de: "Lächeln", category: "Things - General" },
    { en: "smoke", de: "Rauch", category: "Things - General" },
    { en: "sneeze", de: "niesen", category: "Things - General" },
    { en: "snow", de: "Schnee", category: "Things - General" },
    { en: "soap", de: "Seife", category: "Things - General" },
    { en: "society", de: "Gesellschaft", category: "Things - General" },
    { en: "son", de: "Sohn", category: "Things - General" },
    { en: "song", de: "Lied", category: "Things - General" },
    { en: "sort", de: "Sortieren", category: "Things - General" },
    { en: "sound", de: "Klang", category: "Things - General" },
    { en: "soup", de: "Suppe", category: "Things - General" },
    { en: "space", de: "Platz", category: "Things - General" },
    { en: "stage", de: "Bühne", category: "Things - General" },
    { en: "start", de: "Anfang", category: "Things - General" },
    { en: "statement", de: "Erklärung", category: "Things - General" },
    { en: "steam", de: "Dampf", category: "Things - General" },
    { en: "steel", de: "Stahl", category: "Things - General" },
    { en: "step", de: "Schritt", category: "Things - General" },
    { en: "stitch", de: "Stich", category: "Things - General" },
    { en: "stone", de: "Stein", category: "Things - General" },
    { en: "stop", de: "Stop", category: "Things - General" },
    { en: "story", de: "Geschichte", category: "Things - General" },
    { en: "stretch", de: "strecken", category: "Things - General" },
    { en: "structure", de: "Struktur", category: "Things - General" },
    { en: "substance", de: "Substanz", category: "Things - General" },
    { en: "sugar", de: "Zucker", category: "Things - General" },
    { en: "suggestion", de: "Vorschlag", category: "Things - General" },
    { en: "summer", de: "Sommer-", category: "Things - General" },
    { en: "support", de: "Unterstützung", category: "Things - General" },
    { en: "surprise", de: "Überraschung", category: "Things - General" },
    { en: "swim", de: "schwimmen", category: "Things - General" },
    { en: "system", de: "System", category: "Things - General" },
    { en: "talk", de: "sich unterhalten", category: "Things - General" },
    { en: "structure", de: "Struktur", category: "Things - General" },
    { en: "substance", de: "Substanz", category: "Things - General" },
    { en: "sugar", de: "Zucker", category: "Things - General" },
    { en: "suggestion", de: "Vorschlag", category: "Things - General" },
    { en: "summer", de: "Sommer-", category: "Things - General" },
    { en: "support", de: "Unterstützung", category: "Things - General" },
    { en: "surprise", de: "Überraschung", category: "Things - General" },
    { en: "swim", de: "schwimmen", category: "Things - General" },
    { en: "system", de: "System", category: "Things - General" },
    { en: "talk", de: "sich unterhalten", category: "Things - General" },
    { en: "taste", de: "Geschmack", category: "Things - General" },
    { en: "tax", de: "MwSt", category: "Things - General" },
    { en: "teaching", de: "Lehren", category: "Things - General" },
    { en: "tendency", de: "Tendenz", category: "Things - General" },
    { en: "test", de: "Prüfung", category: "Things - General" },
    { en: "theory", de: "Theorie", category: "Things - General" },
    { en: "thing", de: "Ding", category: "Things - General" },
    { en: "thought", de: "habe gedacht", category: "Things - General" },
    { en: "thunder", de: "Donner", category: "Things - General" },
    { en: "time", de: "Zeit", category: "Things - General" },
    { en: "tin", de: "Zinn", category: "Things - General" },
    { en: "top", de: "oben", category: "Things - General" },
    { en: "touch", de: "berühren", category: "Things - General" },
    { en: "trade", de: "Handel", category: "Things - General" },
    { en: "transport", de: "Transport", category: "Things - General" },
    { en: "trick", de: "Trick", category: "Things - General" },
    { en: "trouble", de: "Ärger", category: "Things - General" },
    { en: "turn", de: "Wende", category: "Things - General" },
    { en: "twist", de: "Twist", category: "Things - General" },
    { en: "unit", de: "Einheit", category: "Things - General" },
    { en: "use", de: "benutzen", category: "Things - General" },
    { en: "value", de: "Wert", category: "Things - General" },
    { en: "verse", de: "Vers", category: "Things - General" },
    { en: "vessel", de: "Schiff", category: "Things - General" },
    { en: "view", de: "Aussicht", category: "Things - General" },
    { en: "voice", de: "Stimme", category: "Things - General" },
    { en: "walk", de: "gehen", category: "Things - General" },
    { en: "war", de: "Krieg", category: "Things - General" },
    { en: "wash", de: "waschen", category: "Things - General" },
    { en: "waste", de: "Abfall", category: "Things - General" },
    { en: "water", de: "Wasser", category: "Things - General" },
    { en: "wave", de: "Welle", category: "Things - General" },
    { en: "wax", de: "Wachs", category: "Things - General" },
    { en: "way", de: "Weg", category: "Things - General" },
    { en: "weather", de: "Wetter", category: "Things - General" },
    { en: "week", de: "Woche", category: "Things - General" },
    { en: "weight", de: "Gewicht", category: "Things - General" },
    { en: "wind", de: "Wind", category: "Things - General" },
    { en: "wine", de: "Wein", category: "Things - General" },
    { en: "winter", de: "Winter", category: "Things - General" },
    { en: "woman", de: "Frau", category: "Things - General" },
    { en: "wood", de: "Holz", category: "Things - General" },
    { en: "wool", de: "wolle", category: "Things - General" },
    { en: "word", de: "Wort", category: "Things - General" },
    { en: "work", de: "Arbeit", category: "Things - General" },
    { en: "wound", de: "Wunde", category: "Things - General" },
    { en: "writing", de: "Schreiben", category: "Things - General" },
    { en: "year", de: "Jahr", category: "Things - General" },


    { en: "angle", de: "Winkel", category: "Things - Picturable" },
    { en: "ant", de: "Ameise", category: "Things - Picturable" },
    { en: "apple", de: "Apfel", category: "Things - Picturable" },
    { en: "arch", de: "Bogen", category: "Things - Picturable" },
    { en: "arm", de: "Arm", category: "Things - Picturable" },
    { en: "army", de: "Heer", category: "Things - Picturable" },
    { en: "baby", de: "Baby", category: "Things - Picturable" },
    { en: "bag", de: "Tasche", category: "Things - Picturable" },
    { en: "ball", de: "Ball", category: "Things - Picturable" },
    { en: "band", de: "Band", category: "Things - Picturable" },
    { en: "basin", de: "Becken", category: "Things - Picturable" },
    { en: "basket", de: "Korb", category: "Things - Picturable" },
    { en: "bath", de: "Bad", category: "Things - Picturable" },
    { en: "bed", de: "Bett", category: "Things - Picturable" },
    { en: "bee", de: "Biene", category: "Things - Picturable" },
    { en: "bell", de: "Glocke", category: "Things - Picturable" },
    { en: "berry", de: "Beere", category: "Things - Picturable" },
    { en: "bird", de: "Vogel", category: "Things - Picturable" },
    { en: "blade", de: "Klinge", category: "Things - Picturable" },
    { en: "board", de: "Tafel", category: "Things - Picturable" },
    { en: "boat", de: "Boot", category: "Things - Picturable" },
    { en: "bone", de: "Knochen", category: "Things - Picturable" },
    { en: "book", de: "Buch", category: "Things - Picturable" },
    { en: "boot", de: "Stiefel", category: "Things - Picturable" },
    { en: "bottle", de: "Flasche", category: "Things - Picturable" },
    { en: "box", de: "Box", category: "Things - Picturable" },
    { en: "boy", de: "Junge", category: "Things - Picturable" },
    { en: "brain", de: "Gehirn", category: "Things - Picturable" },
    { en: "brake", de: "Bremse", category: "Things - Picturable" },
    { en: "branch", de: "Ast", category: "Things - Picturable" },
    { en: "brick", de: "Backstein", category: "Things - Picturable" },
    { en: "bridge", de: "Brücke", category: "Things - Picturable" },
    { en: "brush", de: "Bürste", category: "Things - Picturable" },
    { en: "bucket", de: "Eimer", category: "Things - Picturable" },
    { en: "bulb", de: "Birne", category: "Things - Picturable" },
    { en: "button", de: "Taste", category: "Things - Picturable" },
    { en: "cake", de: "Kuchen", category: "Things - Picturable" },
    { en: "camera", de: "Kamera", category: "Things - Picturable" },
    { en: "card", de: "Karte", category: "Things - Picturable" },
    { en: "cart", de: "Wagen", category: "Things - Picturable" },
    { en: "carriage", de: "Wagen", category: "Things - Picturable" },
    { en: "cat", de: "Katze", category: "Things - Picturable" },
    { en: "chain", de: "Kette", category: "Things - Picturable" },
    { en: "cheese", de: "Käse", category: "Things - Picturable" },
    { en: "chest", de: "Truhe", category: "Things - Picturable" },
    { en: "chin", de: "Kinn", category: "Things - Picturable" },
    { en: "church", de: "Kirche", category: "Things - Picturable" },
    { en: "circle", de: "Kreis", category: "Things - Picturable" },
    { en: "clock", de: "Uhr", category: "Things - Picturable" },
    { en: "cloud", de: "Wolke", category: "Things - Picturable" },
    { en: "coat", de: "Mantel", category: "Things - Picturable" },
    { en: "collar", de: "Halsband", category: "Things - Picturable" },
    { en: "comb", de: "Kamm", category: "Things - Picturable" },
    { en: "cord", de: "Kabel", category: "Things - Picturable" },
    { en: "cow", de: "Kuh", category: "Things - Picturable" },
    { en: "cup", de: "Tasse", category: "Things - Picturable" },
    { en: "curtain", de: "Vorhang", category: "Things - Picturable" },
    { en: "cushion", de: "Kissen", category: "Things - Picturable" },
    { en: "dog", de: "Hund", category: "Things - Picturable" },
    { en: "door", de: "Tür", category: "Things - Picturable" },
    { en: "drain", de: "ablassen", category: "Things - Picturable" },
    { en: "drawer", de: "Schublade", category: "Things - Picturable" },
    { en: "dress", de: "Kleid", category: "Things - Picturable" },
    { en: "drop", de: "fallen", category: "Things - Picturable" },
    { en: "ear", de: "Ohr", category: "Things - Picturable" },
    { en: "egg", de: "Ei", category: "Things - Picturable" },
    { en: "engine", de: "Motor", category: "Things - Picturable" },
    { en: "eye", de: "Auge", category: "Things - Picturable" },
    { en: "face", de: "Gesicht", category: "Things - Picturable" },
    { en: "farm", de: "Bauernhof", category: "Things - Picturable" },
    { en: "feather", de: "Feder", category: "Things - Picturable" },
    { en: "finger", de: "Finger", category: "Things - Picturable" },
    { en: "fish", de: "Fisch", category: "Things - Picturable" },
    { en: "flag", de: "Flagge", category: "Things - Picturable" },
    { en: "floor", de: "Fußboden", category: "Things - Picturable" },
    { en: "fly", de: "Fliege", category: "Things - Picturable" },
    { en: "foot", de: "Fuß", category: "Things - Picturable" },
    { en: "fork", de: "Gabel", category: "Things - Picturable" },
    { en: "fowl", de: "Geflügel", category: "Things - Picturable" },
    { en: "frame", de: "Rahmen", category: "Things - Picturable" },
    { en: "garden", de: "Garten", category: "Things - Picturable" },
    { en: "girl", de: "Mädchen", category: "Things - Picturable" },
    { en: "glove", de: "Handschuh", category: "Things - Picturable" },
    { en: "goat", de: "Ziege", category: "Things - Picturable" },
    { en: "gun", de: "Gewehr", category: "Things - Picturable" },
    { en: "hair", de: "Haar", category: "Things - Picturable" },
    { en: "hammer", de: "Hammer", category: "Things - Picturable" },
    { en: "hand", de: "Hand", category: "Things - Picturable" },
    { en: "hat", de: "Hut", category: "Things - Picturable" },
    { en: "head", de: "Kopf", category: "Things - Picturable" },
    { en: "heart", de: "Herz", category: "Things - Picturable" },
    { en: "hook", de: "Haken", category: "Things - Picturable" },
    { en: "horn", de: "Horn", category: "Things - Picturable" },
    { en: "horse", de: "Pferd", category: "Things - Picturable" },
    { en: "hospital", de: "Krankenhaus", category: "Things - Picturable" },
    { en: "house", de: "Haus", category: "Things - Picturable" },
    { en: "island", de: "Insel", category: "Things - Picturable" },
    { en: "jewel", de: "Juwel", category: "Things - Picturable" },
    { en: "kettle", de: "Kessel", category: "Things - Picturable" },
    { en: "key", de: "Schlüssel", category: "Things - Picturable" },
    { en: "knee", de: "Knie", category: "Things - Picturable" },
    { en: "knife", de: "Messer", category: "Things - Picturable" },
    { en: "knot", de: "Knoten", category: "Things - Picturable" },
    { en: "leaf", de: "Blatt", category: "Things - Picturable" },
    { en: "leg", de: "Bein", category: "Things - Picturable" },
    { en: "library", de: "Bibliothek", category: "Things - Picturable" },
    { en: "line", de: "Linie", category: "Things - Picturable" },
    { en: "lip", de: "Lippe", category: "Things - Picturable" },
    { en: "lock", de: "sperren", category: "Things - Picturable" },
    { en: "map", de: "Karte", category: "Things - Picturable" },
    { en: "match", de: "Spiel", category: "Things - Picturable" },
    { en: "monkey", de: "Affe", category: "Things - Picturable" },
    { en: "moon", de: "Mond", category: "Things - Picturable" },
    { en: "mouth", de: "Mund", category: "Things - Picturable" },
    { en: "muscle", de: "Muskel", category: "Things - Picturable" },
    { en: "nail", de: "Nagel", category: "Things - Picturable" },
    { en: "neck", de: "Hals", category: "Things - Picturable" },
    { en: "needle", de: "Nadel", category: "Things - Picturable" },
    { en: "nerve", de: "Nerv", category: "Things - Picturable" },
    { en: "net", de: "Netz", category: "Things - Picturable" },
    { en: "nose", de: "Nase", category: "Things - Picturable" },
    { en: "nut", de: "Nuss", category: "Things - Picturable" },
    { en: "office", de: "Büro", category: "Things - Picturable" },
    { en: "orange", de: "Orange", category: "Things - Picturable" },
    { en: "oven", de: "Ofen", category: "Things - Picturable" },
    { en: "parcel", de: "Paket", category: "Things - Picturable" },
    { en: "pen", de: "Stift", category: "Things - Picturable" },
    { en: "pencil", de: "Bleistift", category: "Things - Picturable" },
    { en: "picture", de: "Bild", category: "Things - Picturable" },
    { en: "pig", de: "Schwein", category: "Things - Picturable" },
    { en: "pin", de: "Stift", category: "Things - Picturable" },
    { en: "pipe", de: "Rohr", category: "Things - Picturable" },
    { en: "plane", de: "Flugzeug", category: "Things - Picturable" },
    { en: "plate", de: "Teller", category: "Things - Picturable" },
    { en: "plough", de: "Pflug", category: "Things - Picturable" },
    { en: "plow", de: "Pflug", category: "Things - Picturable" },
    { en: "pocket", de: "Tasche", category: "Things - Picturable" },
    { en: "pot", de: "Topf", category: "Things - Picturable" },
    { en: "potato", de: "Kartoffel", category: "Things - Picturable" },
    { en: "prison", de: "Gefängnis", category: "Things - Picturable" },
    { en: "pump", de: "Pumpe", category: "Things - Picturable" },
    { en: "rail", de: "Schiene", category: "Things - Picturable" },
    { en: "rat", de: "Ratte", category: "Things - Picturable" },
    { en: "receipt", de: "Kassenbon", category: "Things - Picturable" },
    { en: "ring", de: "Ring", category: "Things - Picturable" },
    { en: "rod", de: "Stange", category: "Things - Picturable" },
    { en: "roof", de: "Dach", category: "Things - Picturable" },
    { en: "root", de: "Wurzel", category: "Things - Picturable" },
    { en: "sail", de: "Segel", category: "Things - Picturable" },
    { en: "school", de: "Schule", category: "Things - Picturable" },
    { en: "scissors", de: "Schere", category: "Things - Picturable" },
    { en: "screw", de: "Schraube", category: "Things - Picturable" },
    { en: "seed", de: "Samen", category: "Things - Picturable" },
    { en: "sheep", de: "Schaf", category: "Things - Picturable" },
    { en: "shelf", de: "Regal", category: "Things - Picturable" },
    { en: "ship", de: "Schiff", category: "Things - Picturable" },
    { en: "shirt", de: "Hemd", category: "Things - Picturable" },
    { en: "shoe", de: "Schuh", category: "Things - Picturable" },
    { en: "skin", de: "Haut", category: "Things - Picturable" },
    { en: "skirt", de: "Rock", category: "Things - Picturable" },
    { en: "snake", de: "Schlange", category: "Things - Picturable" },
    { en: "sock", de: "Socke", category: "Things - Picturable" },
    { en: "spade", de: "Spaten", category: "Things - Picturable" },
    { en: "sponge", de: "Schwamm", category: "Things - Picturable" },
    { en: "spoon", de: "Löffel", category: "Things - Picturable" },
    { en: "spring", de: "Frühling", category: "Things - Picturable" },
    { en: "square", de: "Quadrat", category: "Things - Picturable" },
    { en: "stamp", de: "Stempel", category: "Things - Picturable" },
    { en: "star", de: "Star", category: "Things - Picturable" },
    { en: "station", de: "Bahnhof", category: "Things - Picturable" },
    { en: "stem", de: "Stengel", category: "Things - Picturable" },
    { en: "stick", de: "Stock", category: "Things - Picturable" },
    { en: "stocking", de: "Strumpf", category: "Things - Picturable" },
    { en: "stomach", de: "Bauch", category: "Things - Picturable" },
    { en: "store", de: "Geschäft", category: "Things - Picturable" },
    { en: "street", de: "Straße", category: "Things - Picturable" },
    { en: "sun", de: "Sonne", category: "Things - Picturable" },
    { en: "table", de: "Tabelle", category: "Things - Picturable" },
    { en: "tail", de: "Schwanz", category: "Things - Picturable" },
    { en: "thread", de: "Faden", category: "Things - Picturable" },
    { en: "throat", de: "Kehle", category: "Things - Picturable" },
    { en: "thumb", de: "Daumen", category: "Things - Picturable" },
    { en: "ticket", de: "Fahrkarte", category: "Things - Picturable" },
    { en: "toe", de: "Zehe", category: "Things - Picturable" },
    { en: "tongue", de: "Zunge", category: "Things - Picturable" },
    { en: "tooth", de: "Zahn", category: "Things - Picturable" },
    { en: "town", de: "Stadt, Dorf", category: "Things - Picturable" },
    { en: "train", de: "Zug", category: "Things - Picturable" },
    { en: "tray", de: "Tablett", category: "Things - Picturable" },
    { en: "tree", de: "Baum", category: "Things - Picturable" },
    { en: "trousers", de: "Hose", category: "Things - Picturable" },
    { en: "umbrella", de: "Regenschirm", category: "Things - Picturable" },
    { en: "wall", de: "Wand", category: "Things - Picturable" },
    { en: "watch", de: "sehen", category: "Things - Picturable" },
    { en: "wheel", de: "Rad", category: "Things - Picturable" },
    { en: "whip", de: "Peitsche", category: "Things - Picturable" },
    { en: "whistle", de: "pfeifen", category: "Things - Picturable" },
    { en: "window", de: "Fenster", category: "Things - Picturable" },
    { en: "wing", de: "Flügel", category: "Things - Picturable" },
    { en: "wire", de: "Draht", category: "Things - Picturable" },
    { en: "worm", de: "Wurm", category: "Things - Picturable" },

    { en: "able", de: "fähig", category: "Qualities - General" },
    { en: "acid", de: "Acid", category: "Qualities - General" },
    { en: "angry", de: "wütend", category: "Qualities - General" },
    { en: "automatic", de: "automatisch", category: "Qualities - General" },
    { en: "beautiful", de: "schön", category: "Qualities - General" },
    { en: "black", de: "schwarz", category: "Qualities - General" },
    { en: "boiling", de: "Sieden", category: "Qualities - General" },
    { en: "bright", de: "hell", category: "Qualities - General" },
    { en: "broken", de: "gebrochen", category: "Qualities - General" },
    { en: "brown", de: "braun", category: "Qualities - General" },
    { en: "cheap", de: "billig", category: "Qualities - General" },
    { en: "chemical", de: "chemisch", category: "Qualities - General" },
    { en: "chief", de: "Chef", category: "Qualities - General" },
    { en: "clean", de: "reinigen", category: "Qualities - General" },
    { en: "clear", de: "klar", category: "Qualities - General" },
    { en: "common", de: "verbreitet", category: "Qualities - General" },
    { en: "complex", de: "Komplex", category: "Qualities - General" },
    { en: "conscious", de: "bewusst", category: "Qualities - General" },
    { en: "cut", de: "Schnitt", category: "Qualities - General" },
    { en: "deep", de: "tief", category: "Qualities - General" },
    { en: "dependent", de: "abhängig", category: "Qualities - General" },
    { en: "early", de: "früh", category: "Qualities - General" },
    { en: "elastic", de: "elastisch", category: "Qualities - General" },
    { en: "electric", de: "elektrisch", category: "Qualities - General" },
    { en: "equal", de: "gleich", category: "Qualities - General" },
    { en: "fat", de: "Fett", category: "Qualities - General" },
    { en: "fertile", de: "fruchtbar", category: "Qualities - General" },
    { en: "first", de: "zuerst", category: "Qualities - General" },
    { en: "fixed", de: "Fest", category: "Qualities - General" },
    { en: "flat", de: "eben", category: "Qualities - General" },
    { en: "free", de: "kostenlos", category: "Qualities - General" },
    { en: "frequent", de: "häufig", category: "Qualities - General" },
    { en: "full", de: "voll", category: "Qualities - General" },
    { en: "general", de: "Allgemeines", category: "Qualities - General" },
    { en: "good", de: "gut", category: "Qualities - General" },
    { en: "great", de: "großartig", category: "Qualities - General" },
    { en: "grey", de: "grau", category: "Qualities - General" },
    { en: "gray", de: "grau", category: "Qualities - General" },
    { en: "hanging", de: "hängend", category: "Qualities - General" },
    { en: "happy", de: "glücklich", category: "Qualities - General" },
    { en: "hard", de: "schwer", category: "Qualities - General" },
    { en: "healthy", de: "gesund", category: "Qualities - General" },
    { en: "high", de: "hoch", category: "Qualities - General" },
    { en: "hollow", de: "hohl", category: "Qualities - General" },
    { en: "important", de: "wichtig", category: "Qualities - General" },
    { en: "kind", de: "nett", category: "Qualities - General" },
    { en: "like", de: "mögen", category: "Qualities - General" },
    { en: "living", de: "Leben", category: "Qualities - General" },
    { en: "long", de: "lange", category: "Qualities - General" },
    { en: "male", de: "männlich", category: "Qualities - General" },
    { en: "married", de: "verheiratet", category: "Qualities - General" },
    { en: "material", de: "Material", category: "Qualities - General" },
    { en: "medical", de: "medizinisch", category: "Qualities - General" },
    { en: "military", de: "Militär-", category: "Qualities - General" },
    { en: "natural", de: "natürlich", category: "Qualities - General" },
    { en: "necessary", de: "notwendig", category: "Qualities - General" },
    { en: "new", de: "Neu", category: "Qualities - General" },
    { en: "normal", de: "normal", category: "Qualities - General" },
    { en: "open", de: "öffnen", category: "Qualities - General" },
    { en: "parallel", de: "parallel", category: "Qualities - General" },
    { en: "past", de: "Vergangenheit", category: "Qualities - General" },
    { en: "physical", de: "physikalisch", category: "Qualities - General" },
    { en: "political", de: "politisch", category: "Qualities - General" },
    { en: "poor", de: "Arm", category: "Qualities - General" },
    { en: "possible", de: "möglich", category: "Qualities - General" },
    { en: "present", de: "vorhanden", category: "Qualities - General" },
    { en: "private", de: "Privat", category: "Qualities - General" },
    { en: "probable", de: "wahrscheinlich", category: "Qualities - General" },
    { en: "quick", de: "schnell", category: "Qualities - General" },
    { en: "quiet", de: "ruhig", category: "Qualities - General" },
    { en: "ready", de: "bereit", category: "Qualities - General" },
    { en: "red", de: "rot", category: "Qualities - General" },
    { en: "regular", de: "regulär", category: "Qualities - General" },
    { en: "responsible", de: "verantwortlich", category: "Qualities - General" },
    { en: "right", de: "richtig", category: "Qualities - General" },
    { en: "round", de: "runden", category: "Qualities - General" },
    { en: "same", de: "gleich", category: "Qualities - General" },
    { en: "second", de: "zweite", category: "Qualities - General" },
    { en: "separate", de: "trennen", category: "Qualities - General" },
    { en: "serious", de: "ernst", category: "Qualities - General" },
    { en: "sharp", de: "Scharf", category: "Qualities - General" },
    { en: "smooth", de: "glatt", category: "Qualities - General" },
    { en: "sticky", de: "klebrig", category: "Qualities - General" },
    { en: "stiff", de: "steif", category: "Qualities - General" },
    { en: "straight", de: "Gerade", category: "Qualities - General" },
    { en: "strong", de: "stark", category: "Qualities - General" },
    { en: "sudden", de: "plötzlich", category: "Qualities - General" },
    { en: "sweet", de: "Süss", category: "Qualities - General" },
    { en: "tall", de: "hoch", category: "Qualities - General" },
    { en: "thick", de: "dick", category: "Qualities - General" },
    { en: "tight", de: "fest", category: "Qualities - General" },
    { en: "tired", de: "müde", category: "Qualities - General" },
    { en: "TRUE", de: "WAHR", category: "Qualities - General" },
    { en: "violent", de: "heftig", category: "Qualities - General" },
    { en: "waiting", de: "warten", category: "Qualities - General" },
    { en: "warm", de: "warm", category: "Qualities - General" },
    { en: "wet", de: "nass", category: "Qualities - General" },
    { en: "wide", de: "breit", category: "Qualities - General" },
    { en: "wise", de: "weise", category: "Qualities - General" },
    { en: "yellow", de: "Gelb", category: "Qualities - General" },
    { en: "young", de: "jung", category: "Qualities - General" },

    { en: "awake", de: "Erwachen", category: "Qualities - Opposites" },
    { en: "bad", de: "Schlecht", category: "Qualities - Opposites" },
    { en: "bent", de: "gebogen", category: "Qualities - Opposites" },
    { en: "bitter", de: "bitter", category: "Qualities - Opposites" },
    { en: "blue", de: "Blau", category: "Qualities - Opposites" },
    { en: "certain", de: "sicher", category: "Qualities - Opposites" },
    { en: "cold", de: "kalt", category: "Qualities - Opposites" },
    { en: "complete", de: "Komplett", category: "Qualities - Opposites" },
    { en: "cruel", de: "grausam", category: "Qualities - Opposites" },
    { en: "dark", de: "dunkel", category: "Qualities - Opposites" },
    { en: "dead", de: "tot", category: "Qualities - Opposites" },
    { en: "dear", de: "sehr geehrter", category: "Qualities - Opposites" },
    { en: "delicate", de: "zart", category: "Qualities - Opposites" },
    { en: "different", de: "anders", category: "Qualities - Opposites" },
    { en: "dirty", de: "schmutzig", category: "Qualities - Opposites" },
    { en: "dry", de: "trocken", category: "Qualities - Opposites" },
    { en: "false", de: "falsch", category: "Qualities - Opposites" },
    { en: "feeble", de: "schwach", category: "Qualities - Opposites" },
    { en: "female", de: "weiblich", category: "Qualities - Opposites" },
    { en: "foolish", de: "töricht", category: "Qualities - Opposites" },
    { en: "future", de: "Zukunft", category: "Qualities - Opposites" },
    { en: "green", de: "Grün", category: "Qualities - Opposites" },
    { en: "ill", de: "krank", category: "Qualities - Opposites" },
    { en: "last", de: "zuletzt", category: "Qualities - Opposites" },
    { en: "late", de: "spät", category: "Qualities - Opposites" },
    { en: "left", de: "links", category: "Qualities - Opposites" },
    { en: "loose", de: "lose", category: "Qualities - Opposites" },
    { en: "loud", de: "laut", category: "Qualities - Opposites" },
    { en: "low", de: "niedrig", category: "Qualities - Opposites" },
    { en: "mixed", de: "gemischt", category: "Qualities - Opposites" },
    { en: "narrow", de: "eng", category: "Qualities - Opposites" },
    { en: "old", de: "alt", category: "Qualities - Opposites" },
    { en: "opposite", de: "Gegenteil", category: "Qualities - Opposites" },
    { en: "public", de: "Öffentlichkeit", category: "Qualities - Opposites" },
    { en: "rough", de: "Rau", category: "Qualities - Opposites" },
    { en: "sad", de: "traurig", category: "Qualities - Opposites" },
    { en: "safe", de: "sicher", category: "Qualities - Opposites" },
    { en: "secret", de: "Geheimnis", category: "Qualities - Opposites" },
    { en: "short", de: "kurz", category: "Qualities - Opposites" },
    { en: "shut", de: "geschlossen", category: "Qualities - Opposites" },
    { en: "simple", de: "einfach", category: "Qualities - Opposites" },
    { en: "slow", de: "schleppend", category: "Qualities - Opposites" },
    { en: "small", de: "klein", category: "Qualities - Opposites" },
    { en: "soft", de: "Sanft", category: "Qualities - Opposites" },
    { en: "solid", de: "solide", category: "Qualities - Opposites" },
    { en: "special", de: "Besondere", category: "Qualities - Opposites" },
    { en: "strange", de: "seltsam", category: "Qualities - Opposites" },
    { en: "thin", de: "dünn", category: "Qualities - Opposites" },
    { en: "white", de: "Weiß", category: "Qualities - Opposites" },
    { en: "wrong", de: "falsch", category: "Qualities - Opposites" },

]